<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Svid</AssemblyName>
    <RootNamespace>Svid</RootNamespace>
    <ApplicationIcon>..\assets\app-icon.ico</ApplicationIcon>
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3277</MSBuildWarningsAsMessages>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\build\svdc-backend.exe" LogicalName="svdc-backend.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
  </ItemGroup>
</Project>
