<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SvidSetup</AssemblyName>
    <RootNamespace>Svid.Setup</RootNamespace>
    <ApplicationIcon>..\assets\app-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\dist\Svid.exe" LogicalName="Svid.exe" />
  </ItemGroup>
</Project>
